[package]
name = "zebar"
version = "0.0.0"
description = "Zebar is a tool for creating customizable and cross-platform taskbars, desktop widgets, and popups."
authors = ["you"]
license = ""
repository = ""
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "2.0", features = [] }

[dependencies]
anyhow = "1"
async-trait = "0.1"
clap = { version = "4", features = ["derive"] }
reqwest = { version = "0.11", features = ["json"] }
tauri = { version = "2.0", features = [
  "devtools",
  "macos-private-api",
  "protocol-asset",
  "tray-icon",
] }
tauri-plugin-dialog = "2.0"
tauri-plugin-http = "2.0"
tauri-plugin-shell = "2.0"
tauri-plugin-single-instance = "2.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
starship-battery = "0.8"
sysinfo = "0.30"
tokio = { version = "1.33", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
netdev = "0.24"
regex = "1"
base64 = "0.22.1"
mime = "0.3.17"
mime_guess = "2.0.5"

[target.'cfg(target_os = "windows")'.dependencies]
komorebi-client = { git = "https://github.com/LGUG2Z/komorebi", tag = "v0.1.28" }
windows = { version = "0.58", features = [
  "Win32_Globalization",
  "Win32_System_Console",
  "Win32_System_SystemServices",
  "Win32_UI_WindowsAndMessaging",
  "Win32_UI_Input_KeyboardAndMouse",
  "Win32_UI_TextServices",
  "Win32_NetworkManagement_WiFi",
] }

[target.'cfg(target_os = "macos")'.dependencies]
cocoa = "0.25"

[features]
# This feature is used for production builds or when `devPath` points to the
# filesystem. Do not remove!
custom-protocol = ["tauri/custom-protocol"]
